###
GET http://localhost:3000

###
POST http://localhost:3000/api/register
Content-Type: application/json

{
"fullName": "ben zero",
"email": "ben@zeroppp.com",
"password": "123456"
}

###
POST http://localhost:3000/api/login
Content-Type: application/json

{
"email": "ben@zeroppp.com",
"password": "123456"
}

###
GET http://localhost:3000/api/question

###
POST http://localhost:3000/api/question
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjYsImlhdCI6MTY1ODkxMzUzNCwiZXhwIjoxNjU4OTE3MTM0fQ.wtfmwgHMwv86tYAQDZ4Z7swU64nR022ZzfrMFVgApTc
Content-Type: application/json

{
  "title":"tr",
  "content":"normal"
}
###
PATCH  http://localhost:3000/api/question/9
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjYsImlhdCI6MTY1ODkxMzUzNCwiZXhwIjoxNjU4OTE3MTM0fQ.wtfmwgHMwv86tYAQDZ4Z7swU64nR022ZzfrMFVgApTc
Content-Type: application/json

{
  "title":"ca",
  "content":"very not nicepice"
}
###
DELETE http://localhost:3000/api/question/9
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjYsImlhdCI6MTY1ODkxMzkwMCwiZXhwIjoxNjU4OTE3NTAwfQ.BiuA-ZCAPMN5V0e3h8n7rqnpc6a8MknlKWwG1qKB3qc
Content-Type: application/json

###
GET http://localhost:3000/api/question/1/answers
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjYsImlhdCI6MTY1ODkxMzkwMCwiZXhwIjoxNjU4OTE3NTAwfQ.BiuA-ZCAPMN5V0e3h8n7rqnpc6a8MknlKWwG1qKB3qc
Content-Type: application/json

###
POST http://localhost:3000/api/question/3/answers
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjYsImlhdCI6MTY1ODkxMzkwMCwiZXhwIjoxNjU4OTE3NTAwfQ.BiuA-ZCAPMN5V0e3h8n7rqnpc6a8MknlKWwG1qKB3qc
Content-Type: application/json

{
  "answer":"ve"
}

